import { config } from "dotenv";
import axios from "axios";

config();

const API_URL = "https://api.deepseek.com/chat/completions";
const API_KEY = process.env.DEEPSEEK_API_KEY;

/**
 * Uses DeepSeek AI to analyze environmental data.
 * This service constructs a structured prompt that guides the AI in analyzing air quality sensor data.
 *
 * @param {Object} inputData - Contains sensorData, modelResponse, and AQI.
 * @returns {Promise<string>} - The analysis text generated by DeepSeek AI.
 */
export async function analyzeDataWithDeepSeek(inputData) {
    try {
        // Define system instructions for the AI.
        const systemPrompt = `You are an advanced AI specializing in environmental and air quality monitoring for the Smart AiQuality Management System.
Analyze the provided sensor data, including pollutant levels, AQI, and health risk indicators.
- Identify trends over time (e.g., rising or falling pollution levels).
- Detect anomalies (e.g., sudden spikes in pollutants or unusual patterns).
- Provide insights into possible causes of observed trends based on data.
- Offer health and safety recommendations based on AQI levels and health risks.
- Do not alter or modify any numerical sensor measurements.
- Format your response in clear, structured paragraphs for easy understanding by non-technical users.
- Keep the explanation precise, actionable, and based on the latest available data.`;

        // Convert input data to a JSON string for clarity.
        const userPrompt = JSON.stringify(inputData, null, 2);

        // Send request to DeepSeek AI
        const response = await axios.post(
            API_URL,
            {
                model: "deepseek-chat",
                messages: [
                    { role: "system", content: systemPrompt },
                    { role: "user", content: userPrompt }
                ]
            },
            {
                headers: {
                    "Authorization": `Bearer ${API_KEY}`,
                    "Content-Type": "application/json"
                }
            }
        );

        // Return AI-generated analysis
        return response.data.choices[0].message.content;
    } catch (error) {
        console.error("Error:", error.response ? error.response.data : error.message);
        throw new Error("Failed to analyze data with DeepSeek AI");
    }
}
